import { valueMgr as vm } from "../deps.ts";
import { TextArtifactNature } from "../nature.ts";

export const sqlArtifact = new (class implements TextArtifactNature {
  readonly isTextArtifactNature = true;
  readonly name = "SQL";
  readonly defaultFileExtn: string = ".sql";
  readonly fileExtensions: string[] = [this.defaultFileExtn];
  readonly defaultPreamble: vm.TextValue =
    "-- Code generated by Netspective IGS. DO NOT EDIT.\n\n";

  constructor() {}
})();

export const postgreSqlArtifact = new (class implements TextArtifactNature {
  readonly isTextArtifactNature = true;
  readonly name = "PostgreSQL";
  readonly defaultFileExtn: string = ".psql";
  readonly fileExtensions: string[] = [this.defaultFileExtn];
  readonly defaultPreamble: vm.TextValue =
    "-- Code generated by Netspective IGS. DO NOT EDIT.\n\n";

  constructor() {}
})();

export const plantUmlArtifact = new (class implements TextArtifactNature {
  readonly isTextArtifactNature = true;
  readonly name = "PlantUML";
  readonly defaultFileExtn: string = ".puml";
  readonly fileExtensions: string[] = [this.defaultFileExtn];
  readonly defaultPreamble: vm.TextValue =
    "// Code generated by Netspective IGS. DO NOT EDIT.\n\n";

  constructor() {}
})();

export const yamlArtifact = new (class implements TextArtifactNature {
  readonly isTextArtifactNature = true;
  readonly name = "YAML";
  readonly defaultFileExtn: string = ".yaml";
  readonly fileExtensions: string[] = [this.defaultFileExtn, ".yml"];
  readonly defaultPreamble: vm.TextValue =
    "# Code generated by Netspective IGS. DO NOT EDIT.\n\n";

  constructor() {}
})();

export const dockerfileArtifact = new (class implements TextArtifactNature {
  readonly isTextArtifactNature = true;
  readonly name = "Dockerfile";
  readonly defaultFileExtn: string = ".dockerfile";
  readonly fileExtensions: string[] = [this.defaultFileExtn];
  readonly defaultPreamble: vm.TextValue =
    "# Code generated by Netspective IGS. DO NOT EDIT.\n\n";

  constructor() {}
})();

export const jsonArtifact = new (class implements TextArtifactNature {
  readonly isTextArtifactNature = true;
  readonly name = "JSON";
  readonly defaultFileExtn: string = ".json";
  readonly fileExtensions: string[] = [this.defaultFileExtn];

  constructor() {}
})();

export const shfileArtifact = new (class implements TextArtifactNature {
  readonly isTextArtifactNature = true;
  readonly name = "SH";
  readonly defaultFileExtn: string = ".sh";
  readonly fileExtensions: string[] = [this.defaultFileExtn];
  readonly defaultPreamble: vm.TextValue =
    "# Code generated by Netspective IGS. DO NOT EDIT.\n\n";

  constructor() {}
})();
